### ISSUE TITLE
Blameable needs extra code/configuration undocumented

### ISSUE THREAD

**Issue by rodrigobb** [doctrine-extensions/DoctrineExtensions#1048]
At least listener in .yml

```
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
```

and section (similar to loggable) in 'DoctrineExtensionListener' class:

```
    public function onKernelRequest(GetResponseEvent $event)
    {
        $securityContext = $this->container->get('security.context', ContainerInterface::NULL_ON_INVALID_REFERENCE);
        if (null !== $securityContext && null !== $securityContext->getToken() && $securityContext->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
[...]
            $blameable = $this->container->get('gedmo.listener.blameable');
            $blameable->setUserValue($securityContext->getToken()->getUser());
        }
    }

```
