### ISSUE TITLE
sluggable umlauts/accents and the order of transliterate and urlize

### ISSUE THREAD

**Issue by sebastianreloaded** [doctrine-extensions/DoctrineExtensions#1065]
Im using sluggable in my project. since i have to generate slugs from titles with umlauts in it, i expected that "ä" would be converted to "ae" etc.
Looking at the Urlizer class the function "urlize/unaccent" would do exactly that. But in "generateSlug" of SluggableListener the call for "urlize" is after the "transliterate" call. And "transliterate" calls "utf8ToAscii" which replaces all "ä" with just "a".

Im not sure whether i really understand the concept of the handlers, transliterate and urlize. can anybody enlighten me?

**Comment by cklm** [comment]
@sebastianreloaded works even in Symfony3 - thank you!

**Comment by l3pp4rd** [comment]
well, people have different needs for this kind of behavior, as you have found out, it is fairly simple to customize.

**Comment by l3pp4rd** [comment]
What I suggest you to do is to use custom transliteration function:

``` php
$sluggableListener->setTransliterator(['YourStaticTransliteratorClass', 'staticTranslaterationMethod']);
```

Or with symfony dependency injection

``` yaml
services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setTransliterator, [["YourStaticTransliteratorClass", "staticTranslaterationMethod"]]]
```

The changes to library cannot be applied since it affects users, it allows you to customize transliteration without a need to extend listener - which is also a proper solution.

**Comment by onlime** [comment]
You're right, this is a nasty BC break.

I do not like to write my own `gedmo.listener.*` service definitions and prefer enabling the listeners via StofDoctrineExtensionsBundle. Way simpler to integrate.

I do know how to use my own Transliterator and already have it running in my Symfony project

```php
<?php
namespace AppBundle\Listener;

use Gedmo\Sluggable\SluggableListener as GedmoSluggableListener;
use Gedmo\Sluggable\Util\Urlizer;

class SluggableListener extends GedmoSluggableListener
{
    public function __construct()
    {
        $this->setTransliterator(array('\AppBundle\Listener\SluggableListener', 'transliterate'));
    }

    /**
     * Since transliterate will convert "ä" to an "a", I added this hack to call
     * unaccent first so it is converted to "ae" first.
     *
     * @param string $text
     * @param string $separator
     * @return string $text
     */
    public static function transliterate($text, $separator = '-')
    {
        $text = Urlizer::unaccent($text);
        $text = Urlizer::transliterate($text, $separator);

        return $text;
    }
}
```
and:

```yaml
# app/config/config.yml

stof_doctrine_extensions:
    class:
        sluggable: AppBundle\Listener\SluggableListener
```

But... I don't think this is very newbie-friendly. Couldn't you add it to the configuration options for slug annotation? e.g.:
- unaccent (optional, default=false)

That would be very handy and I am sure most of the users would love to enable the unaccent option.
Thanks for this great bundle!
Cheers, Philip
