### ISSUE TITLE
Loggable - How to use data.

### ISSUE THREAD

**Issue by DougHayward** [doctrine-extensions/DoctrineExtensions#1112]
So I've successfully setup the bundle and have got my entity setup as below:
## Products.orm.yml

```
ACME\DemoBundle\Entity\Product:
type: entity
table: Product
gedmo:
  loggable: true

id:
    id:
        type: integer
        generator: { strategy: AUTO }
fields:

#Some other fields#

       cost:
         type: decimal
         presision: 10
         scale: 4
       nullable: true
       gedmo:
          - versioned
```

Which stores in the database all fine and well adding rows to the 'ext_log_entries' table. However the field holding the data I need looks like this:

```
a:1:{s:4:"cost";d:14.9499999;}
```

Now I'm hazarding a guess at this being 'serialized data'? But how do I make use of it? 
What I need is just the figure 14.95 as I wish to use the numbers to make price change graphs.
Is it either possible to make the bundle save logs instead of using the 'Data' column have a 'Cost' column only containing the cost figure? Or do I need to somehow extract the data required... if so, how would I go about it?

Any help much appreciated.
Doug.
