### ISSUE TITLE
Translatable. Integrity constraint violation: 1062 Duplicate entry on a ManyToMany record update/persist

### ISSUE THREAD

**Issue by leftdevel** [doctrine-extensions/DoctrineExtensions#113]
Hi. 
I'm getting this excpetion message 

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-3' for key 'PRIMARY'
```

Where 5 and 3 are both primary keys of Bedroom entity and Tag entity respectively on a ManyToMany association.This error is thrown when trying to update bedroom's tags (adding a new tag).

This is not happening when creating a new Bedroom and adding tags to it. Also, it is not happening when removing a Tag from a Bedroom.

I rolled back my changes to not support Translatable, and everything works ok.This is happening regardless if the current app locale is 'en' or 'es'.The way I'm filling the entity's data  is through Symfony2 PR4 Forms.

Bedroom entity' doctrine mapping is:

```
Oscar\HotelBundle\Entity\Bedroom:
    type:  entity
    table:  bedroom
    gedmo:
        translation:
            locale: locale
    id:
        id:
            type:  integer
            generator:
                strategy:  AUTO
    fields:
        name:
            type:  string
            length:  100
            gedmo:
                - translatable
        description:
            type:  text
            gedmo:
                - translatable
        price:
            type:  decimal(5)
            scale:  2

    manyToOne:
        category:
            targetEntity: Oscar\HotelBundle\Entity\Cateory
            inversedBy: bedrooms
    manyToMany:
        tags:
          targetEntity: Oscar\HotelBundle\Entity\Tag
          inversedBy: habitaciones
          joinTable:
            name: bedroom_tag
            cascade: ["persist", "remove"]
            joinColumns:
              bedroom_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id

```

The exception will be thrown also for simple fixtures:

```
        $category= $em->getRepository('HotelBundle:Category')->find(1);
        $category2= $em->getRepository('HotelBundle:Category')->find(2);
        $tag=$em->getRepository('HotelBundle:Tag')->find(1);
        $tag2=$em->getRepository('HotelBundle:Tag')->find(2);

        $bedroom = new Bedroom();

        $bedroom->setName('none');
        $bedroom->setDescription('none');
        $bedroom->setCategory($category);
        $bedroom->setPrice(10);

        $em->persist($bedroom);
        $em->flush();

        #code above persist a new bedroom, next code will update the bedroom.

        $bedroom->getTags()->add($tag);
        $bedroom->setName('another name');
        $bedroom->setDescription('another desc');
        $bedroom->setPrice(11); 
        $bedroom->setCategory($cateogry2); 

        $em->persist($bedroom);
        $em->flush();

```

Something tricky is that if I don't update name, description, price and category properties, updating bedroom's tags will succeed. If I try to update all properties but not tags, it will also succeed. Recap. Just adding a tag is not working (deleting is ok).

I notice that symfony profiler says that insert command is being executed twice, (also delete command ).

```
INSERT INTO bedroom_tag (bedroom_id, tag_id) VALUES (?, ?)
Parameters: [4, 2]
Time: 0.89 ms
INSERT INTO bedroom_tag (bedroom_id, tag_id) VALUES (?, ?)
Parameters: [4, 2]
```

This exception is broking my app, as I have one form for updating bedroom's simple properties, its category  and its tags. What I will do for now is to have a dedicated form for a bedroom's tags related actions.

I'm using Symfony2 RC4.

My best regards!
