### ISSUE TITLE
Disable softdeleteable filter not working

### ISSUE THREAD

**Issue by reypm** [doctrine-extensions/DoctrineExtensions#1159]
I'm trying to disable the filter from a Repository class and I can't, I got this message instead:

> Filter 'soft-deleteable' is not enabled.

Filter is enabled as the `config.yml` shows:

```
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            ci_type: Tanane\FrontendBundle\DBAL\Types\CIType
            rif_type: Tanane\FrontendBundle\DBAL\Types\RifType
            shipping_from_type: Tanane\FrontendBundle\DBAL\Types\SFType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
            auto_mapping: true
            filters:
                softdeleteable:
                  class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                  enabled: true

# Doctrine Ext
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable:  true
            softdeleteable: true
```

This is how I'm disabling the filter:

```
public function findIncludingSoftdeletedBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
{
    // disabled softdeleteable filter
    $this->getEntityManager()->getFilters()->disable('soft-deleteable');

    // return regular "findBy" including softdeleted users
    return $this->findBy($criteria, $orderBy, $limit, $offset);
}
```

Any advice?
