### ISSUE TITLE
[Sluggable] SluggableListener shows notice when using slug with unique flag

### ISSUE THREAD

**Issue by torchello** [doctrine-extensions/DoctrineExtensions#116]
I'm not sure that I understood problem correctly, but try to explain.

I have entity with such yaml config:

``` yaml
[...skipped...]
    alias:
      type: string(50)
      fixed: false
      nullable: false
      gedmo:
        - slug
    originalName:
      type: string(50)
      fixed: false
      nullable: false
      column: original_name
      gedmo:
        sluggable:
          slugField: alias
[...skipped...]
```

When I try to persist new entity I get notice:

``` php
Notice: Undefined index: slug in /var/www/goalsX/sf.37goals.com/Symfony/vendor/gedmo-doctrine-extensions/lib/Gedmo/Sluggable/SluggableListener.php line 319
```

Changing config to:

``` yaml
    alias:
      type: string(50)
      fixed: false
      nullable: false
      gedmo:
        slug:
          unique: false
```

fixes this problem. I suppose that problem exists as far as my field name differs from default (slug). But I'm not sure...
