### ISSUE TITLE
Allow SoftDeleteable to consider 0000-00-00 00:00:00 be equivalent to null

### ISSUE THREAD

**Issue by mrthehud** [doctrine-extensions/DoctrineExtensions#1169]
When using SoftDeleteable with an entity that has a unique constraint, such as a User with an "email" column, it's handy to be able to modify the unique constraint to be a composite of "email" and "deleted" so that when an entity is soft deleted, the email address becomes available again.

Unfortunately, as SoftDeleteable uses null to represent 'not deleted', the unique constraint doesn't work, as MySQL considers NULL != NULL.

Thus, if the "deleted" column could use "0000-00-00 00:00:00" as the 'not deleted' value, or default, such a composite key would function as intended.

Perhaps a config setting such as:

``` yaml
doctrine:
    orm:
        filters:
            softdeleteable:
                default: value_for_default
```

where value_for_default is either null or '0000-00-00 00:00:00' 

Would that be possible and sane, or is there some other way to achieve this easily?
