### ISSUE TITLE
IpTraceable always "Null"

### ISSUE THREAD

**Issue by pdias** [doctrine-extensions/DoctrineExtensions#1174]
Hello,

I'm trying record the IP of the user (my user extends fosuser) , each time he login. I'm using ip_traceable with **Symfony2**.

This is part of my **entity**:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 * @Gedmo\Loggable
 * @UniqueEntity(fields="email", message="user.email.already_taken")
 * @UserAssert\isDeleted(property="email")
 */
class User extends BaseUser implements UserInterface
{
   .....

   /**
     * @var string $fromIp
     *
     * @Gedmo\IpTraceable
     * @ORM\Column(name="fromIp", type="string", nullable=true, length=45)
     */
    protected $fromIp;


    ......

}
```

In my **config.yml** i have added this:

```
services:
    # KernelRequest listener
    extension.listener:
        class: WebBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
            # loggable hooks user username if one is in security context
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            #- [ setDefaultLocale, [ %default_locale% ] ]
            #- [ setTranslationFallback, [ true ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.iptraceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
```

In my **Kernel Request Listener** (**WebBundle\Listener\DoctrineExtensionListener**) i have:

```
.......
public function onKernelRequest(GetResponseEvent $event)
    {
        $securityContext = $this->container->get('security.context', ContainerInterface::NULL_ON_INVALID_REFERENCE);
        if (null !== $securityContext && null !== $securityContext->getToken() && $securityContext->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $loggable = $this->container->get('gedmo.listener.loggable');
            $loggable->setUsername($securityContext->getToken()->getUsername());
        }

        $ip = $event->getRequest()->getClientIp();
        if (null !== $ip) {
            $ipTraceable = $this->container->get('gedmo.listener.iptraceable');
            $ipTraceable->setIpValue($ip);
        }
    }
```

The **iptraceable** listener is called but my field **fromIp** is always **"null"**.

I have tried this to, but unsuccessfully:

```
/**
     * @var string $fromIp
     *
     * @Gedmo\IpTraceable(on="update")
     * @ORM\Column(name="fromIp", type="string", nullable=true, length=45)
     */
    protected $fromIp;
```

Can someone help me?

Thanks in advance, 

Paulo
