### ISSUE TITLE
Disable softdeleteable filter doesn't disabled Listeners

### ISSUE THREAD

**Issue by Garfield-fr** [doctrine-extensions/DoctrineExtensions#1175]
I would like to hard-delete a record by disabling the filter but it doesn't work because listeners are already active on my entity.

I find a solution but it's not perfect:

``` php
$manager->getFilters()->disable('softdeleteable');
foreach ($manager->getEventManager()->getListeners() as $eventName => $listeners) {
    foreach ($listeners as $listener) {
        if ($listener instanceof \Gedmo\SoftDeleteable\SoftDeleteableListener) {
            $manager->getEventManager()->removeEventListener($eventName, $listener);
        }
    }
}
```

Do you have another solution ?

Thank's

**Comment by appeltaert** [comment]
same, doesnt seem fixed 1 year later? theres no way to disable them now. @Garfield-fr did you find a solution?

**Comment by max-kovpak** [comment]
You can create your own event listener something like this:
```php
<?php namespace AppBundle\EventListener;

use \Gedmo\SoftDeleteable\SoftDeleteableListener as BaseSoftDeleteableListener;
use Doctrine\Common\EventArgs;

class SoftDeleteableListener extends BaseSoftDeleteableListener
{

    /**
     * @inheritdoc
     */
    public function onFlush(EventArgs $args)
    {
        $ea = $this->getEventAdapter($args);
        $om = $ea->getObjectManager();
        //return from event listener if you disabled filter: $em->getFilters()->disable('softdeleteable');
        if (!$om->getFilters()->isEnabled('softdeleteable')) {
            return;
        }

        parent::onFlush($args);
    }

}
```
in your config:
```yaml
    gedmo.listener.softdeleteable:
        class: AppBundle\EventListener\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
```
