### ISSUE TITLE
Sluggable: Why that translate persian character?

### ISSUE THREAD

**Issue by ghanbari** [doctrine-extensions/DoctrineExtensions#1248]
title & slug mapping:

``` yaml
    fields:
        title: ~
        slug:
            unique: true
            gedmo:
                slug:
                  fields:
                    - title
```

if i enter title in persian language, my slug try for fingilish (persian word with english character).

if i enter title: "اخرین تست شناسه"
then my slug is: "khryn-tst-shnsh"

how can i stop it?,
thanks
