### ISSUE TITLE
Timestampable + yaml + Doctrine Embeddables

### ISSUE THREAD

**Issue by ghost** [doctrine-extensions/DoctrineExtensions#1447]
Hi,
I have tried to use Doctrine Embeddables to include timestampable properties. So I have created this files:

Timestampable.php

```
<?php

namespace Acme\Model;

class Timestampable
{
    protected $created;
    protected $updated;
}
```

Acme.Model.Timestampable.dcm.yml

```
Acme\Model\Timestampable:
  type: embeddable
  fields:
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update

```

Acme.Entity.Message.dcm.yml

```
Acme\Model\Message:
  type: entity
  table: messages
  embedded:
    timestampable:
      class: Acme\Model\Timestampable
      columnPrefix: false
  id:
    id:
      type: string
      nullable: false
  fields:
    .....
```

Message.php

```
<?php

namespace Acme\Model;

abstract class AbstractMessage
{
    protected $id;

    protected $timestampable;

    public function __construct( )
    {
      ....
    }
}

```

The table is created properly, but when I try to insert a record, I get this error:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null
