### ISSUE TITLE
Cannot use object of type Doctrine\ORM\Query\ParserResult as array with Redis Cache

### ISSUE THREAD

**Issue by samplenull** [doctrine-extensions/DoctrineExtensions#1460]
After switching to Redis (php5-redis with SncRedisBundle) for doctrine metadata and query cache, I have this error
Fatal Error (E_ERROR): Cannot use object of type Doctrine\ORM\Mapping\ClassMetadata as array in
vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php:136

I'd appreciate some help.

**Comment by l3pp4rd** [comment]
doctrine extensions are compatible with doctrine, not with third party bundle, the bundle [unserializes and serializes](https://github.com/snc/SncRedisBundle/blob/master/Doctrine/Cache/RedisCache.php#L57) values, doctrine does not. you can override the cache service or use [redis cache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php) from doctrine.

**Comment by samplenull** [comment]
I've switched to native redis cache from doctrine and get the same result

**Comment by l3pp4rd** [comment]
well, on the second look, [config](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Mapping/MappedEventSubscriber.php#L136) is somehow misplaced with doctrine orm metadata. extensions stores array to cache mapping. Have you customized extensions? it seems like cache related, but if it would be an issue in extensions, a lot of people would have raised that. you could try a standard symfony app with this redis bundle, I doubt that it can be library related..

**Comment by samplenull** [comment]
I guess it is very very specific problem, which I even cannot consistently reproduce. Just posted this issue with hope of similar problems from other developer's experiences. 

We use only Translatable extension with almost default options:

```
  orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        metadata_cache_driver: redis
        query_cache_driver: redis
        result_cache_driver: redis
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
                alias: GedmoTranslatable
                is_bundle: false
```
Also after enabling redis cache I keep getting occasional fatals like this:
*Fatal Error (E_ERROR): Call to a member function wakeupReflection() on a non-object in file vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:721*
