### ISSUE TITLE
Sluggable: "unique_base" option with indirect associations

### ISSUE THREAD

**Issue by miguelrs** [doctrine-extensions/DoctrineExtensions#1465]
I have an entity `Role` associated `manyToOne` with an entity `UserType`, which is in turn is associated `manyToOne` with an entity `Account`.

`Role` `==manyToOne==>` `UserType` `==manyToOne==>` `Account`

I would like to generate slugs for my `Role` entity that are unique within an `Account` (not within a `UserType`).  
I'd like something like the following. Would that be possible at all?

```
My\App\Role:
[...]
slug:
    type: string
    gedmo:
        slug:
            fields: [label]
            unique: true
            unique_base: userType.account
            updatable: false
[...]
```

I could add another direct association directly between `Role` and `Account`, but I think that'd be redundant data...
