### ISSUE TITLE
The class 'Gedmo\Tool\Wrapper\EntityWrapper' was not found in the chain configured namespaces Gedmo\Loggable\Entity

### ISSUE THREAD

**Issue by zak10** [doctrine-extensions/DoctrineExtensions#1513]
I've been searching high and low and can't seem to figure this one out. Here is my mapping:

```
entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
```

This used to work until upgrading to symfony 2.8. tried reverting gedmo from dev-master to 2.3.\* and it still didn't work. What am I missing?

**Comment by Wobbly-Wibbly** [comment]
Seems like you're missing indentation after 
```
gedmo_loggable:
    type: annotation
    prefix: Gedmo\Loggable\Entity
    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
    alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
    is_bundle: false
```

**Comment by zak10** [comment]
@Wobbly-Wibbly that was actually just a formatting issue, my config looks as you posted it. I can't seem to figure this one out!

**Comment by jverdeyen** [comment]
Any update on this? I'm having the same issue from a command.

**Comment by l3pp4rd** [comment]
have you went through to [documentation examples](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md#mapping) ?

**Comment by l3pp4rd** [comment]
try to skip alias, and it is not a bundle!

``` yaml
entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
```
