### ISSUE TITLE
[iptraceable] Symfony2 Default Authentication Handler triggered before IP is set

### ISSUE THREAD

**Issue by fliespl** [doctrine-extensions/DoctrineExtensions#1520]
iptraceable should start service with higher priority. In my case 10 was enough. In my example i was logging ips of user on successful login inside AuthenticationHandler.

```
services:
    extension.listener:
        class: AppBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            # as soon as possible (before authentication handler)
            - { name: kernel.event_listener, event: kernel.request, method: onEarlyKernelRequest, priority: 10 }
```

```
    public function onEarlyKernelRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();
        if ($request) {
            $ip = $request->getClientIp();

            if (null !== $ip) {
                $iptraceable = $this->container->get('gedmo.listener.iptraceable');
                $iptraceable->setIpValue($ip);
            }
        }
    }
```
