### ISSUE TITLE
[Documentation] Fix slug field length

### ISSUE THREAD

**Issue by ghost** [doctrine-extensions/DoctrineExtensions#1603]
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sluggable.md

`slug` has a length of 128. 
`title` has a length of 64.
`code` has a length of 16.

The example use camel-case with one character as seperator:

```
      gedmo:
        slug:
          separator: _
          style: camel
          fields:
            - title
            - code
```

So the length of the field `slug` should be 16+64+1 = 81 and not 128.
