### ISSUE TITLE
[Translatable] wrong content onFlush event when local != defaultLocale

### ISSUE THREAD

**Issue by nnmer** [doctrine-extensions/DoctrineExtensions#1641]
Let say, i have 3 locales.
en
zh_CN
zh_HK

My default locale is: en.

I use https://github.com/lunetics/LocaleBundle to simplify my frontend locale switching. It works correctly, no problem.

The problem is in translatable onFlush event.
When my locale==en and defaultLocale==en then everything work correctly, i have correct records of translations in the DB. But when locale != defaultLocale, let say, locale==en and defaultLocale==zh_CN the record of zh_CN in the DB become equal to en!

Tracking down the issue, i found that translation reflection taking "locale" version of the content
It is here: https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/TranslatableListener.php#L663

If i comment the rows 663:684 (in v2.4.19 that is 628:649) then my translations are saved correctly to DB.

Whether i'm missing something? Why that happens?
my gedmo translatable service setup is:

```
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ true ] ]
            - [ setPersistDefaultLocaleTranslation, [ true ] ]
```
