### ISSUE TITLE
[Translatable] Translations do not update with symfony forms

### ISSUE THREAD

**Issue by NikitaKharkov** [doctrine-extensions/DoctrineExtensions#1782]
Good day! I can't update my translations with forms with `PATCH` request. I have next structure

```
# MyDocument
    /**
     * @var integer $id
     *
     * @ODM\Id(strategy="INCREMENT")
     * @ODM\Index(unique=true)
     *
     * @JMS\Expose
     * @JMS\Type("integer")
     */
    protected $id;
/**
     * @var string $externalCancelCondition
     *
     * @ODM\Field(type="string")
     *
     * @Gedmo\Translatable
     * @JMS\Expose
     * @JMS\Type("string")
     */
    protected $externalCancelCondition;

    /**
     * @var string $externalCancelPricePolice
     *
     * @ODM\Field(type="string")
     *
     * @Gedmo\Translatable
     * @JMS\Expose
     * @JMS\Type("string")
     */
    protected $externalCancelPricePolice;

   /**
     * @ODM\ReferenceMany(targetDocument="AppBundle\Document\Translation\QuotaTranslation", mappedBy="object", cascade={"persist", "remove"})
     *
     * @JMS\Expose
     * @JMS\Accessor(getter="getTranslationsToJson")
     */
    protected $translations;
```
```
# MyController
$document = new MyDocument();
$form = $this->createForm(MyFormType::class, $document, ['method' => 'PATCH']);
$form->submit($request->request->all(), false);
```

```
# MyFormType
$builder
    ...some other fields...
    ->add('translations', CollectionType::class, array(
              'entry_type' => MyTranslationType::class,
              'allow_add' => true,
              'allow_delete' => true,
     ))
```

```
# MyTranslationsType
$builder
            ->add('locale', TextType::class)
            ->add('field', TextType::class)
            ->add('content', TextType::class)
        ;
```

```
# config.yml
doctrine_mongodb:
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: mongodb://%mongo_host%:%mongo_port%
            options:
                username: %mongo_user%
                password: %mongo_password%
                db: %mongo_auth_database%
    default_database: %mongo_database%
    document_managers:
        default:
            auto_mapping: true
            mappings:
              translatable:
                type: annotation
                is_bundle: false
                prefix: Gedmo\Translatable\Document
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
                alias: GedmoTranslatable

stof_doctrine_extensions:
    mongodb:
        default:
            timestampable: true
            softdeleteable: true
            translatable: true
```

So when I try to send `PATCH` request to update I got object with snapshot, which contains all correct translations. But after flushing I saw old objects...
When I create translations everything is ok. 
I spent many time to find solution, but couldn't... Thanks!
