### ISSUE TITLE
gedmo settings on associationOverride doctrine mapping

### ISSUE THREAD

**Issue by stefandoorn** [doctrine-extensions/DoctrineExtensions#1793]
It seems the gedmo settings are ignored on the 'associationOverride' doctrine mapping usage, like below. The associationOverride is loaded, but gedmo doesn't seem to use it's group afterwards to define the positions. Am I overlooking something, or is this not supported?

```
    associationOverride:
        option:
            targetEntity: Sylius\Component\Product\Model\ProductOptionInterface
            inversedBy: values
            joinColumn:
                option_id:
                    referencedColumnName: id
                    nullable: true
                    onDelete: cascade
            gedmo:
                - sortableGroup
```
