### ISSUE TITLE
Is there any way to convert all fields loggable?

### ISSUE THREAD

**Issue by roberto910907** [doctrine-extensions/DoctrineExtensions#1816]
The point is that I need to track the changes of all my entities, but I have 12 bundle with almost 260 database tables and I dont want to mark every field of every entity with @Versioned annotation. Is there any way to mark my entities as Loggable without marking each field as Versioned? I expected something more easy, I think that the most uses cases is all the fields are versioned and just exclude some of them. Sorry for my bad english.

**Comment by l3pp4rd** [comment]
use a different thing then, https://github.com/DATA-DOG/DataDogAuditBundle

**Comment by roberto910907** [comment]
@biji Are you trying to override the [original mapping configuration](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/doctrine-mapping/User.orm.xml)? Maybe you could add the [gedmo's mapping](http://atlantic18.github.io/DoctrineExtensions/doc/loggable.html#xml-mapping) for the field(s) you want.

**Comment by biji** [comment]
Thanks @roberto910907 
 I will try your suggestion, mapping whole configuration

**Comment by biji** [comment]
my issue solved by using attribute overrides, thanks

**Comment by biji** [comment]
I'm not using xml but yaml mapping:
```
    attributeOverride:
        username:
            gedmo: [ versioned ]
        email:
            gedmo: [ versioned ]
        enabled:
            gedmo: [ versioned ]

```

**Comment by k3ssen** [comment]
I had the same question and found this can be achieved by extending the LoggableListener (I'm working with version 2.4.10).

In the config you can refer to your listener class using something like this:
```yaml
stof_doctrine_extensions:
    orm:
        default:
            loggable: true
    class:
        loggable: AppBundle\EventListener\LoggableListener
```
In your own class you can make the listener behave the way you want:

```php
class LoggableListener extends \Gedmo\Loggable\LoggableListener
{
    public function getConfiguration(ObjectManager $objectManager, $class)
    {
        $config = parent::getConfiguration($objectManager, $class);
        if (!isset($config['versioned'])) {
            $classMetadata = $objectManager->getClassMetadata($class);
            $config['versioned'] = $classMetadata->getFieldNames();
        }
        return $config;
    }
```
In this basic example all fields become versioned for all classes that do not already have versioned fields set. Here you can implement your own logic to decide what to use.
