### ISSUE TITLE
[Sortable] Is it possible to have multiple sortablePositions per entity?

### ISSUE THREAD

**Issue by damianprzygodzki** [doctrine-extensions/DoctrineExtensions#1829]
I am trying to take advantage of managing position properties of Sortable Extension to provide independent and iterated properties to sort. These are not depending of any group, just two - sortablePosition.

If i do something like this:
```
   fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
        contentPosition:
            type: integer
            gedmo:
                - sortablePosition
```  
one of **property is getting null.**
