### ISSUE TITLE
Improve documentation (listeners in services.yml)

### ISSUE THREAD

**Issue by vnivuahc** [doctrine-extensions/DoctrineExtensions#1833]
Hi,
I'm using **Timestampable** and **SoftDeleteable** extensions in my 1st Symfony project.
I'm not familiar with Doctrine extensions, and your documentation pages have been very useful.

However, I spent a lot of time to find how to activate the listeners needed by theses extensions. There what I added to my **services.yml** :

```yaml
services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
```

Should be this added in the documentation ? Maybe an oversight ?

(As I said, I'm new in Symfony/Doctrine world. Maybe you have a good reason to not indicate it here. Or maybe I just missed a point..)

Thx for the extensions btw !
