### ISSUE TITLE
Sluggable: make slug unique among the objects with the same unique_base AND the ones with unique_base equals to NULL

### ISSUE THREAD

**Issue by miguelrs** [doctrine-extensions/DoctrineExtensions#1893]
Let's say I have 2 classes `User` and `UserType`.  
Vast majority of users have one type, but there are a few special users that have no type.

I'm using sluggable for `User` like:
```
fields:
    slug:
        type: string
        gedmo:
            slug:
                fields: [fullName]
                unique: true
                unique_base: userType
                updatable: false
```

The problem is I want the slug to be unique among the users of the same type _and_ the users with no type. E.g.,  having these 2 users:
```
User1:
    fullName: John Doe
    userType: Admin

User2:
    fullName: John Doe
    userType: NULL
```
I want them to have different slugs, but they are given the same one, because their `userType` is not the same...

I've been exploring the Sluggable code and I don't think this is possible by default... is that right?  

And if so, can you suggest a good workaround for this?
