### ISSUE TITLE
Is TreeSlugHandler working with Translatable parent field?

### ISSUE THREAD

**Issue by angeldelrio** [doctrine-extensions/DoctrineExtensions#1943]
I'm testing TreeSlugHandle in a self referencing relation, the field used to generate the slug at parent entity is a Translatable and I'm getting unexpected behaviours. Is TreeSlugHandler designed to work on this kind of scenario? Translatables with simple slugs works like a charm

**Comment by AkenRoberts** [comment]
Hello @angeldelrio. It's possible that the specific combination of Translatable + TreeSlugHandler has not been tested.

Could you please share your related entity or entities, and the "unexpected behavior" you're experiencing. Thank you!

**Comment by angeldelrio** [comment]
Hi @AkenRoberts, thanks for your reply.

This is the entity I'm working on:
`
/**
 * @ORM\Entity
 */
class Geo
{    

    /**
     * @ORM\ManyToOne(targetEntity="Geo", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     */
    protected $parent;

    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255, unique=true, nullable=false)
     */
    protected $name;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(type="string", length=255, unique=true, nullable=false)
     * @Gedmo\Translatable
     */
    protected $slug;

    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\TreeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="parentRelationField", value="parent"),
     *          @Gedmo\SlugHandlerOption(name="separator", value="/")
     *      })
     * }, fields={"name"})
     * @ORM\Column(length=64, unique=true, nullable=false)
     * @Gedmo\Translatable
     */
    protected $compositeSlug;

    /**
     * @Gedmo\Locale
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
    protected $locale = 'es';

    /**
     * other columns or methods omitted for clarity
     */
}
`
I have, for example, 3 entities related by self referencing parent relation ($parent property). As you can see the default locale will be 'es', their spanish names are: Europa -> Reino Unido -> Londres

When I persist those entities it works great, $compositeSlug for Londres entity is: /europa/reino-unido/londres, and no changes are made to translations table.

Now I try to translate those entities, so I set locale to 'en' and update their names to: Europe --> United Kingdom --> London and is when I get the unexpected behaviour I mentioned above.

In London, $compositeSlug is saved to translations table correctly (/europe/united-kingdom/london) but in entity table $compositeSlug is persisted as /europe/united-kingdom/londres. It seems parent's slug are being generated in 'en' locale, but the last one on the bottom of the tree is generated in the default 'es' locale.

Thanks in advance!

**Comment by Guite** [comment]
@angeldelrio please also post your settings for `persistDefaultLocaleTranslation` and `translationFallback`

**Comment by angeldelrio** [comment]
Here are my settings at Symfony service definition file for TranslatableListener:
```
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 0} 
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ] #%locale% will be 'es'
            - [ setTranslationFallback, [ false ] ]
```
Thanks!
