### ISSUE TITLE
Loggable extension - Username is null

### ISSUE THREAD

**Issue by csabavirag** [doctrine-extensions/DoctrineExtensions#1949]
I setup the Loggable module with putting the following into config.yml:
```
doctrine:
    orm:
        mappings:
            loggable:
                type: annotation
                alias: GedmoLoggable
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
```
and
```
stof_doctrine_extensions:
    orm:
        default:
            loggable: true
```

Everything is fine, I get the changed made on an entity logged into the ext_log_entries table, however the username column is always null.

I checked, the setUsername is called by `Stof\DoctrineExtensionsBundle\EventListener\LoggerListener::onKernelRequest` function every time I make a call to the website, however as I can see the $this->username value is always null @ https://github.com/Atlantic18/DoctrineExtensions/blob/113a5c0494254d2e29d8b4ebc622dba0c8abe922/lib/Gedmo/Loggable/LoggableListener.php#L283 when createLogEntry is called by onFlush (https://github.com/Atlantic18/DoctrineExtensions/blob/113a5c0494254d2e29d8b4ebc622dba0c8abe922/lib/Gedmo/Loggable/LoggableListener.php#L187)

As I can see the onFlush is always executed earlier than the onKernelRequest setUsername call which passed the right username to LoggableListener.

What did I do wrong?
