### ISSUE TITLE
[Loggable] Deep embeddables 

### ISSUE THREAD

**Issue by ghettovoice** [doctrine-extensions/DoctrineExtensions#1968]
Currently Loggable extension allows versioned embeddable in entity metadata, but doesn't handle versioned embeddables in this embeddable. In other words there is no support of deep loggable embeddables.
Suppose I have UserProfile as embeddable in the User entity, and in the UserProfile value object has an Contact as embeddable value object.

```php
class User {
   /** @var string */
   private $id;
   /** @var UserProfile */
   private $profile;
  ...
}

class UserProfile  {
   /** @var Contact */
   private $contact;
   ...
}

class Contact {
    private $city;  
    private $country;
    ....
}
```

And I have a Mapping:

```yaml
User:
    type: entity
  
    gedmo:
        loggable: true

    fields:
        username:
            gedmo:
                - versioned
  
    embedded:
        profile:
            class: UserProfile
            gedmo:
                - versioned

UserProfile:
    type: embeddable
       
    fields:
        fullName: 
            gedmo:
                - versioned
     

    embedded:
        contact:
            class: Contact
            # currently doen't work
            gedmo:
                - versioned

Contact:
    type: embeddable

    fields:
        city:
            gedmo:
                - versioned
        ...
```

I tried to fix this on my fork, but currently only for YAML driver https://github.com/ghettovoice/DoctrineExtensions/blob/deep-loggable/lib/Gedmo/Loggable/Mapping/Driver/Yaml.php#L149.    
And seems like it works for me and may be useful for others.

Thank you for awesome package!
