### ISSUE TITLE
Gedmo Tree event subscriber + multiple doctrine event subscribers does not work

### ISSUE THREAD

**Issue by yobud** [doctrine-extensions/DoctrineExtensions#2077]
Hi all!

I have the following configuration :

```
gedmo.listener.tree:
    class: Gedmo\Tree\TreeListener
    tags:
        - { name: doctrine.event_subscriber, connection: default, priority: 10 }
    calls:
        - [ setAnnotationReader, [ "@annotation_reader" ] ]

App\EventListener\Doctrine\:
    resource: '../src/EventListener/Doctrine'
    tags:
        - { name: doctrine.event_subscriber, connection: default }
```

If I enable only one of the two declarations, it works. But if I left both uncommented, I've got the following error : 

> Tree listener was not found on your entity manager, it must be hooked into the event manager

Did I do anything wrong ? Changing priority doesn't fix anything.

Thanks for you help,

Jérémy
