### ISSUE TITLE
[Tree] Problem nestedset with doctrine second-level-cache

### ISSUE THREAD

**Issue by Nastro** [doctrine-extensions/DoctrineExtensions#2087]
There is a problem with the nestedset tree working with doctrine second-level-cache.

I create the following nestedset tree via sonata-admin with doctrine second-level-cache enabled:

```
\root
    \branch1
        \leaf11
        \leaf12
    \branch2
        \leaf21
        \leaf22
```
Сreation order is: root, branch1, branch2, leaf11, leaf12, leaf21, leaf22.

As a result, I have such data in database:

```
 id  | root_id | parent_id |  title  | lft | rgt | lvl |  path   |        slug         
-----+---------+-----------+---------+-----+-----+-----+---------+---------------------
 296 |     296 |           | root    |   1 |  14 |   0 | root    | root
 298 |     296 |       296 | branch2 |   2 |  11 |   1 | branch2 | root/branch2
 297 |     296 |       296 | branch1 |  12 |  13 |   1 | branch1 | root/branch1
 299 |     296 |       297 | leaf11  |   9 |  10 |   2 | leaf11  | root/branch1/leaf11
 300 |     296 |       297 | leaf12  |   7 |   8 |   2 | leaf12  | root/branch1/leaf12
 301 |     296 |       298 | leaf21  |   5 |   6 |   2 | leaf21  | root/branch2/leaf21
 302 |     296 |       298 | leaf22  |   3 |   4 |   2 | leaf22  | root/branch2/leaf22
```

It can be seen that branch1 fields `lft` and `rgt` are set to 12 and 13 respectively, that is incorrect because branch1 has 2 children, so its `lft` and `rgt` should differ by no less than 4.

When doctrine second-level-cache is disabled, all the `lfts` and `rgts` are assigned correctly.

It seems that setting `Query::HINT_CACHE_EVICT` hint to `true` for all the update queries in https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Tree/Strategy/ORM/Nested.php fixes the issue.

Is there any other solution that does not require fixing DoctrineExtensions code? Or shall I set new pull-request?

My doctrine config:

```
doctrine:
    orm:
        auto_generate_proxy_classes: true
        metadata_cache_driver: ~
        query_cache_driver:
            type: pool
            pool: doctrine.local_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.local_cache_pool
        second_level_cache:
            enabled: true
            log_enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.local_cache_pool
            regions:
                query_cache_region:
                    cache_driver:
                        type: pool
                        pool: doctrine.local_cache_pool
                timestamp_cache_region:
                    cache_driver:
                        type: pool
                        pool: doctrine.local_cache_pool
                entity_cache_region:
                    cache_driver:
                        type: pool
                        pool: doctrine.local_cache_pool
                relation_cache_region:
                    cache_driver:
                        type: pool
                        pool: doctrine.local_cache_pool
framework:
    cache:
        pools:
            doctrine.local_cache_pool:
                adapter: cache.system
```
The doctrine entity uses `NONSTRICT_READ_WRITE` caching mode to `entity_cache_region`.
