### ISSUE TITLE
SoftDoctrineExtention dont work - subdir is entity namespace ?

### ISSUE THREAD

**Issue by Slandais** [doctrine-extensions/DoctrineExtensions#2154]
Hi,

I use SF 4.4 and `"stof/doctrine-extensions-bundle": "^1.4"`.

I want to use SoftDeleteable doctrine extension but it doesn't work. If I try a remove of the entity, Doctrine use a DELETE query.

My entity have subdir in namespace : 
namespace App\Company\Entity; 
instead of classic 
namespace App\Entity;

Here my config :  

doctrine.yaml : 

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_sqlsrv'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Company:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Company/Entity'
                prefix: 'App\Company\Entity'
                alias: Company
```

stof_doctrine_extensions.yaml :  
```yaml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
```

And the entity : 
```php
<?php

namespace App\Company\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo; // gedmo annotations

/**
 * @ORM\Entity()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true)
 */
class Company extends AbstractTimestampedEntity
{

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

```

Any idea ?

Thanks.
