### ISSUE TITLE
Provide service repositories for Symfony users

### ISSUE THREAD

**Issue by mbabker** [doctrine-extensions/DoctrineExtensions#2440]
`DoctrineBundle` provides a `ServiceEntityRepository` and `DoctrineMongoDBBundle` provides a `ServiceDocumentRepository`, both of which exist to make configuring entity repositories as services a simpler thing.  When using the default `EntityRepository` and `DocumentRepository` respectively, one has to manually configure services for their application, such as this for the `LogEntryRepository` from the Loggable extension:

```yaml
services:
    gedmo.repository.entity.log_entry:
        class: Gedmo\Loggable\Entity\Repository\LogEntryRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [Gedmo\Loggable\Entity\LogEntry]
```

This also means users lose autowiring support if they have repository classes that extend from those provided by this package (such as the `SortableRepository` from the Sortable extension) since that extends the default `EntityRepository`.

It'd be nice if this package provided service repository subclasses as well as the default repository implementations where practical (the inheritance in the Tree extension makes that a little more complicated) which would help consumers in Symfony applications use these repository classes more efficiently.  Another option, if that isn't a desired end-state, would be moving the logic for these repositories into traits and then downstream users could use those traits in their own repositories.

Note, `StofDoctrineExtensionsBundle` doesn't provide services for the repository classes, nor are there any documentation examples here or in the bundle helping users to use these repositories in the context of a Symfony application (which mainly affects the Loggable and Translatable extensions since those have standalone entities and repositories, the other extensions with repositories provide add-on capabilities for existing entities so those repositories are designed to be extended).
