### ISSUE TITLE
Blameable: was not found in the chain configured namespaces App\Entity

### ISSUE THREAD

**Issue by ma-gu-16** [doctrine-extensions/DoctrineExtensions#2500]
Hi,

want to use blameable as follow: 

using symfony 5.4 FLEX

The class 'Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage' was not found in the chain configured namespaces App\Entity

![image](https://user-images.githubusercontent.com/22169074/183088014-ebe43e8f-c5e9-40a1-81cd-4d82e471cce6.png)

after i added it as follows:

services.yaml
```

    Gedmo\Blameable\BlameableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, ['@annotation_reader']]
            - [ setUserValue, ['@security.token_storage'] ]
 
```

abstract enitity class: 

![image](https://user-images.githubusercontent.com/22169074/183088363-9f189fdc-6e1e-4a7b-91d5-2b0367006adf.png)

Hope for some hints or solutions :) 
nice weekend.

**Comment by ma-gu-16** [comment]
i made it like this: 

and changed the class with contructor. 

```

    App\Listener\BlameableListener:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, ['@annotation_reader']]



```
