### ISSUE TITLE
timestampable listener not active/not working

### ISSUE THREAD

**Issue by alessandro-podo** [doctrine-extensions/DoctrineExtensions#2501]
I am not sure why and dont know how to debug this. 

When i use the "Gedmo\Timestampable\Traits\TimestampableEntity;" i always got the Form Error, that the Value can't be null. 

The "TimestampableListener" isnt active. Checked via "console debug:event-dispatcher  |grep Stof"

This 2 Listener i can see: 
```
#21     Stof\DoctrineExtensionsBundle\EventListener\LoggerListener::onKernelRequest()                  0         
#22     Stof\DoctrineExtensionsBundle\EventListener\BlameListener::onKernelRequest()                   0    
```

My Config: 
```yaml
stof_doctrine_extensions:
    default_locale: de_DE
    orm:
        lokal: 
            timestampable: true
            loggable: true
            blameable: true
```
