### ISSUE TITLE
Loggable doesn't write in the database

### ISSUE THREAD

**Issue by JoDarma-lp** [doctrine-extensions/DoctrineExtensions#2520]
I want to use loogable extension, but it doesn't write anything in `ext_log_enties` table. 

I'm using symfony 5.4 and Api-platform 2.6.8 in my project.

My configuration: 

`doctrine.yaml`

```
doctrine:
    dbal:
        types:
            datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
            datetime: \Carbon\Doctrine\DateTimeType
        url: '%env(resolve:DATABASE_URL)%'
        wrapper_class: App\Doctrine\DynamicWorkspaceConnection
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                is_bundle: false
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            userteam_allowed:
                class: App\Filter\AllowedByConnectedUserFilter
```

`stof_doctrine_extensions.yaml`
```
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sortable: true
            timestampable: true
            blameable: false
            softdeleteable: true
            loggable: true
```
`User.php`

```
#[Gedmo\Loggable]
class User implements UserInterface
{
     /**
     * @ORM\Column(type="string", length=128, nullable=false)
     */
    #[Gedmo\Versioned]
    private ?string $firstName = null;

    /**
     * @ORM\Column(type="string", length=128, nullable=false)
     */
    #[Gedmo\Versioned]
    private ?string $lastName = null;
}
```

`service.yaml` :
```
services:
 ...
  gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
```
What's wrong in my configuration ?
