### ISSUE TITLE
Attributes with custom MetadataDriver

### ISSUE THREAD

**Issue by zim32** [doctrine-extensions/DoctrineExtensions#2521]
Good day. 

I have a custom doctrine mapping driver. When I try to use Translatable **attribute** with my entities, it is not working, because this extension fallbacks to Annotation driver instead of Attribute driver by default.

Here it is: 
https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Mapping/ExtensionMetadataFactory.php#L170

Is it possible to configure this somehow? Maybe it should decide default driver based on **type** of mapping?

```
mappings:
    gedmo_translatable:
        type: attribute
        prefix: Gedmo\Translatable\Entity
```

What do you think?
