### ISSUE TITLE
Can't load IpTraceable 

### ISSUE THREAD

**Issue by Vic-M** [doctrine-extensions/DoctrineExtensions#2526]
Hello, I'm trying to use the IpTraceable extension but the config is not recognized. I'm using symfony 6 and in config/packages/stof_doctrine_extensions.yaml, I have

```
stof_doctrine_extensions:
    default_locale: en_US
    orm:
      default:
        timestampable: true
        ip_traceable: true
```

When I run the code, I get:

![image](https://user-images.githubusercontent.com/32042587/197622910-c05dfcf2-b27a-49d8-9bd4-f071b64667d6.png)

How do I enable the extension? Thanks!
