### ISSUE TITLE
[SoftDeleteable] Issue setting up SoftDeleteableFilter & SoftDeleteableListener

### ISSUE THREAD

**Issue by jbnemanja** [doctrine-extensions/DoctrineExtensions#2535]
I'm having issues with setting up SoftDeleteableFilter & SoftDeleteableListener. Soft delete works, my entities gets an updated deletedAt field on remove, but I can't figure out how to set up a soft delete filter. I'm using symfony 5.4

This is my config/packages/doctrine.yaml file:
```yaml

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
```

This is my config/packages/stof_doctrine_extensions.yaml file:

```yaml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
```

And this is my config/services.yaml file:

```yaml
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

When I try to delete some entity, it works fine, it updates deletedAt field. But, I want to add softdeleteable filter, and that's when the things stop working. I added gedmo.listener.softdeleteable service to services.yaml and filters part to doctrine.yaml, and i get this error:

```
Listener "SoftDeleteableListener" was not added to the EventManager!
```
