### ISSUE TITLE
[Timestampable] not-null violation on create

### ISSUE THREAD

**Issue by drekinov** [doctrine-extensions/DoctrineExtensions#2565]
Hi,
We get not-null sql violation from time to time when one specific entity is created.
It is happening randomly without any obvious pattern.

Entity is table inheritance with 
```php
#[ORM\InheritanceType(value: 'SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'discr', type: Types::STRING)]
#[ORM\DiscriminatorMap([.....])

//...

 #[ORM\Column(name: 'created_at', type: Types::DATETIMETZ_IMMUTABLE, nullable: false)]
    #[Gedmo\Timestampable(on: 'create')]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIMETZ_IMMUTABLE, nullable: false)]
    #[Gedmo\Timestampable(on: 'update')]
    private DateTimeImmutable $updatedAt;
```

It happen on production with following prod specific config for doctrine (i think it is default for symfony 6.x):

```yaml
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            metadata_cache_driver:
                type: pool
                pool: cache.doctrine_metadata
            query_cache_driver:
                type: pool
                pool: cache.doctrine_query
            result_cache_driver:
                type: pool
                pool: cache.doctrine_result
```

i recall it started after switching to php attributes with Symfony 5.3+-. Right now app is Symfony 6.2 and it continue to appear as randomly as before.

Fix which i apply is to flush redis database holding prod caches + execute CLI commands which should do the same + restart all messenger workers so they get new cache / empty cache.

I have no idea what is wrong or where to start debug for last 6+ months.

Database is postgresql 14.x
