### ISSUE TITLE
The dependency on doctrine/annotations should become optional

### ISSUE THREAD

**Issue by stof** [doctrine-extensions/DoctrineExtensions#2683]
## Feature Request

For projects that have migrated from annotations to attributes (as recommended by the Doctrine team), the `doctrine/annotations` package is unnecessary.
As the Doctrine team is planning to mark the `doctrine/annotations` package as abandoned (see https://github.com/doctrine/annotations/issues/485), it would be great if this package could stop being a mandatory dependency of the extensions.

**Comment by mbabker** [comment]
See #2554 as it has a more complete rundown of where the issues lie.

**Comment by stof** [comment]
since this issue has been created, support for attributes has been implemented.
So for PHP 8+, attributes could be used to solve the issue:
- loggable and translatable provides mapping both using annotations and attributes now
- the helper methods could rely on those existing attributes to register an attribute driver instead of an annotations one
- ExtensionMetadataFactory could be creating a default attribute reader instead.

To me, the main blocker is actually the support for PHP 7.x. Maybe it is time to bump the min PHP version to 8.0 (or maybe 8.1 to be able to use enums in #2675 instead).

Note also that doctrine/orm 3.0 is dropping the annotation driver entirely, so you will have to do this migration to attributes before supporting ORM 3.0 (or making a conditional migration)

**Comment by mbabker** [comment]
#2559 deals with the helpers.

As you pointed out, attributes exist now, and leaving the annotations in place won't hurt anything for the time being, so that one's adequately covered for now.

I think realistically the remaining hard dependencies are the non-nullable `$annotationReader` argument of the `ExtensionMetadataFactory` constructor (including the logic in `MappedEventSubscriber::getExtensionMetadataFactory()` which tries to create a default annotation reader to provide the factory if one doesn't exist) and inherently changing its `getDriver()` method to throw if it tries to use an annotation or attribute based driver without that dependency being passed in (as the way the method reads to me right now, if you're using a XML or YAML mapping driver, you should never reach the code paths where the reader would be required, so that's already a bit of an over-reaching constructor requirement).

**Comment by tacman** [comment]
Any update on this?   I've removed doctrine/annotations from a project, so of course this fails.  

```yaml
services:
  gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ '@annotation_reader' ] ]
```

**Comment by mbabker** [comment]
Symfony won't have a native annotations reader but it won't block your project from upgrading.  If you're manually configuring services as your pre-edit comment suggests, you can use the `Gedmo\Mapping\Driver\AttributeReader` class in those `setAnnotationReader` method calls.

**Comment by tacman** [comment]
Is there an alias for that?  I can't seem to find it.  What should @annotation_reader be?

```yaml
services:
  gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
      # I have 2 DBAL connections using Timestampable
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ '@annotation_reader' ] ]

```

**Comment by tacman** [comment]
I'm hacking in services.yaml, but this is a bit of a mystery to me:

```yaml
    attr_reader: "@Gedmo\\Mapping\\Driver\\AttributeReader"
    Gedmo\Mapping\Driver\AttributeReader:
        alias: attribute_reader
```

Etc. 

It seems like this would be better as the default, and someone could set the annotation reader if they were using them.  There was a significant refactoring of this bundle a while ago to support attributes.  

I'm mostly trying to silence deprecation warnings, which are practically blocking the real issues.
