### ISSUE TITLE
[Loggable] Incomplete documentation on how to use custom LogEntry entity

### ISSUE THREAD

**Issue by Tetragramat** [doctrine-extensions/DoctrineExtensions#2751]
Documentation https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/loggable.md

Contains how custom LogEntry entity should look, but what should be configured for it to work is completely missing.

I'm really struggling here. I though I figured it out, but ended with getting logged one change twice with the same version number.

Using with `stof/doctrine-extensions-bundle`, but it should be documented here too.

**Comment by Tetragramat** [comment]
Found out the issue.

To have custom LogEntry entity used as default one you must create custom entity as defined in https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/loggable.md#custom-logentry-class and then extend `\Gedmo\Loggable\LoggableListener`.

```php
class LoggableListener extends \Gedmo\Loggable\LoggableListener
{
	protected function getLogEntryClass(LoggableAdapter $ea, $class)
	{
		return self::$configurations[$this->name][$class]['logEntryClass'] ?? CustomLogEntry::class;
	}

	protected function prePersistLogEntry($logEntry, $object)
	{
		// set up additional fields in CustomLogEntry
	}
}
```

If you use `stof/doctrine-extensions-bundle`.

```yaml
stof_doctrine_extensions:
    orm:
        default:
            loggable: true
    class:
        loggable: 'App\EventListener\LoggableListener' # your extended listener
        
services:
    # register extended listener as alias to make sure your autoconfiguration does not register it twice
    App\EventListener\LoggableListener: '@stof_doctrine_extensions.listener.loggable'
```
