### ISSUE TITLE
Unable to configure SoftDeleteable: Unrecognized options "filters"

### ISSUE THREAD

**Issue by klaussilveira** [doctrine-extensions/DoctrineExtensions#329]
After adding DoctrineExtensions to my application, i'm having some problems configuring it. After adding this to my Doctrine configuration:

```
doctrine:
      orm:
          auto_generate_proxy_classes: %kernel.debug%
          auto_mapping: true
          entity_managers:
              default:
                  filters:
                      softdeleteable:
                          class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                          enabled: true
```

I got: 

```
Unrecognized options "filters" under "doctrine.orm.entity_managers.default"
```
