### ISSUE TITLE
Listener "SoftDeleteableListener" was not added to the EventManager! 

### ISSUE THREAD

**Issue by NZRicky** [doctrine-extensions/DoctrineExtensions#380]
Hi, everyone

I followed the instruction 

https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/softdeleteable.md to test softdeteable extension under 

Symfony 2.1.0-DEV, I configured my config.yml like below:
# 

```
orm:
    auto_generate_proxy_classes: %kernel.debug%
    auto_mapping: true
    filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true
    mappings:
        translatable:
            type: annotation
            alias: Gedmo
            prefix: Gedmo\Translatable\Entity
            # make sure vendor library location is correct
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
        loggable:
            type: annotation
            alias: Gedmo
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
        tree:
            type: annotation
            alias: Gedmo
            prefix: Gedmo\Tree\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"   
```
# 

and my controller file:
# 

```
   /**
 * @Route("/del", name="del_article")
 */
public function delAction() {
    $em = $this->getDoctrine()->getEntityManager();

    $article = $em->find('Article', 3);
    $em->remove($article);
            $em->flush();
    die('ok');
}
```
# 

when I run the code, it always show the exception: Listener "SoftDeleteableListener" was not added to the EventManager! 

And I use netbeans xdebug the code, I found that the class "SoftDeleteableFilter" function "getListener()", 
# 

```
        foreach ($evm->getListeners() as $listeners) {
            foreach ($listeners as $listener) {
                if ($listener instanceof SoftDeleteableListener) {
                    $this->listener = $listener;

                    break 2;
                }
            }
        }

        if ($this->listener === null) {
            throw new \RuntimeException('Listener "SoftDeleteableListener" was not added to the EventManager!');
        }
```
# 

the $listeners has no instanceof SoftDeleteableListener, but it has other listeners, such as 

Gedmo\Tree\TreeListener
Gedmo\Sortable\SortableListener
Gedmo\Sluggable\SluggableListener
Gedmo\Loggable\LoggableListener
Gedmo\Timestampable\TimestampableListener
Gedmo\Translatable\TranslatableListener

which all generated from loadClassMetadata, I think it might generate from my doctrine_extensions.yml service listener:
# 

services:
    extension.listener:
        class: Infinitz\UserBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

```
gedmo.listener.tree:
    class: Gedmo\Tree\TreeListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.translatable:
    class: Gedmo\Translatable\TranslatableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
        - [ setDefaultLocale, [ %locale% ] ]
        - [ setTranslationFallback, [ false ] ]

gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.sortable:
    class: Gedmo\Sortable\SortableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]         
```
# 

And I tried to add:
# 

```
gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
```
# 

it still showing "Listener "SoftDeleteableListener" was not added to the EventManager! "....

Do I need to add an listener which instance of SoftDeleteableListener ?

Any help will be very appreciated...Thanks.

**Comment by roberto910907** [comment]
For the record you have to enable the extension:

`stof_doctrine_extensions:
    default_locale: es_ES
    orm:
        default:
            softdeleteable: true    # needed: listeners are not enabled by default
`

**Comment by etshy** [comment]
Just for information, I had this problem with symfony 4.
The documentation was unclear on how to configure the softdeletable (or I misread something).
Here what I had to do (for mongodb though):
```
stof_doctrine_extensions:
  default_locale: fr_FR
  mongodb:
    default:
      softdeleteable: true
```
```
doctrine_mongodb:
    document_managers:
        default:
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter
                    enabled: true
```

```
gedmo.listener.softdeleteable:
      class: Gedmo\SoftDeleteable\SoftDeleteableListener
      tags:
        - { name: doctrine.event_subscriber, connection: default }
```

on the latest code, adding the calls options
```
calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
```
throw an error "not valid yaml"
