### ISSUE TITLE
"You cannot define a mapping item when in a sequence" error

### ISSUE THREAD

**Issue by Venzon** [doctrine-extensions/DoctrineExtensions#381]
I have upadated vendors yesterday and such error occured:

You cannot define a mapping item when in a sequence in "[...]BackendBundle\Resources\config\doctrine\/Entity.orm.yml" 

Stack Trace
1. in [...]\vendor\symfony\symfony\src\Symfony\Component\Yaml\Parser.php at line 114 
2. at Parser ->parse ('- translatable slug: separator: - style: default updatable: true fields: - name ')
   in [...]\vendor\symfony\symfony\src\Symfony\Component\Yaml\Parser.php at line 179
3. at Parser ->parse ('type: string length: 255 gedmo: - translatable slug: separator: - style: default updatable: true fields: - name')
   in [...]\vendor\symfony\symfony\src\Symfony\Component\Yaml\Parser.php at line 179 

Seems that error comes from translatable extension or maybe translation of slug triggers error

working on SF2 vendors older then few days gives me no errors

my definition for translatable slug field:

```
 slug:
      type: string
      length: 255
      gedmo:
        - translatable
        slug:
          separator: -
          style: default
          updatable: true
          fields:
            - name
```

removing translatable fixed error

please help
