### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lft' cannot be null

### ISSUE THREAD

**Issue by Ziiweb** [doctrine-extensions/DoctrineExtensions#389]
Hi,

I'm just following the tutorial for setting up the nested tree behaviour and now i run this:

<?php
$food = new Category();
$food->setTitle('Food');

$fruits = new Category();
$fruits->setTitle('Fruits');
$fruits->setParent($food);

$vegetables = new Category();
$vegetables->setTitle('Vegetables');
$vegetables->setParent($food);

$carrots = new Category();
$carrots->setTitle('Carrots');
$carrots->setParent($vegetables);

$this->em->persist($food);
$this->em->persist($fruits);
$this->em->persist($vegetables);
$this->em->persist($carrots);
$this->em->flush();

But im getting:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lft' cannot be null

Any idea?

Javi

**Comment by httpways** [comment]
I have the same issue.

You said: it has to be connected to event manager

How can we do that ?

**Comment by saadhre** [comment]
Check this example: https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/em.php#L83

**Comment by AmProsius** [comment]
I solved it by configuring the subscriber like this:

```yaml
# config/services.yaml
services:
    # ...

    Gedmo\Tree\TreeListener:
        tags:
            -  name: doctrine.event_subscriber
               connection: default
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

[Source](https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers)
