### ISSUE TITLE
Tree and Loggable behaviors are not really compatible with other behaviors

### ISSUE THREAD

**Issue by dirkluijk** [doctrine-extensions/DoctrineExtensions#428]
Please compare the way gedmo behaviours are configured (like associative arrays):

Sluggable

```
    my_field:
      type: string
      length: 50
      nullable: true
      gedmo:
        slug:
          fields: [name]
          separator: -
          (...)
```

Timestampable:

```
    date_created:
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create
```

But this is not consistent with how for example Tree and Loggable are configured (like a list):

Loggable:

```
    sort_nr:
      type: integer
      nullable: false
      gedmo:
        - sortablePosition
```

Tree:

```
    rgt:
      type: integer
      gedmo:
        - treeRight
```

I want to have this compatible, because I use ORM Designer for designing my models and want to add support for these extensions. Now the definition is not consistent. This would for example be better:

```
    rgt:
      type: integer
      gedmo:
          treeRight: ~
```
