### ISSUE TITLE
[Sluggable] consider adding "fieldSeparator" option

### ISSUE THREAD

**Issue by jonathaningram** [doctrine-extensions/DoctrineExtensions#470]
Couldn't find any issue history for this feature, but essentially here is some sample mapping in YAML:

``` yaml
        slug:
            # ...
            gedmo:
                slug:
                    unique: false
                    updatable: true
                    # New option
                    fieldSeparator: /
                    # Current option and default value
                    separator: -
                    fields:
                        - organizationName
                        - repositoryName
```

Then, for `organizationName="Acme Corp"` and `repositoryName="Test Project"`, the slug would be generated as `acme-corp/test-project`.

What do you think?
