### ISSUE TITLE
Translatable Slug not working

### ISSUE THREAD

**Issue by rubbik** [doctrine-extensions/DoctrineExtensions#542]
Hello,

I'm new in SF2 and trying to reproduce the news system I had in SF1.4

The Translatable & Sluggable behaviors works perfectly on their side but when using them together, the slug is not translated and stay on the default locale.

I'm looking for a solution since yesterday and I think I maybe do something wrong but I cannot figure out what.

Here is my "News" entity : 

/**
- Idw\NewsBundle\Entity\News
  *
- @ORM\Table()
- @Gedmo\TranslationEntity(class="Idw\NewsBundle\Entity\NewsTranslation")
- @Gedmo\Loggable
- @Gedmo\SoftDeleteable(fieldName="deleted_at")
- @ORM\Entity(repositoryClass="Idw\NewsBundle\Entity\NewsRepository")
  */
  class News
  {
  // ... some code ...
  
  /**
  - @var string $title
  - @Gedmo\Translatable
  - @ORM\Column(name="title", type="string", length=255)
    */
    private $title;
  
  /**
  - @var string $slug
  - @Gedmo\Slug(fields={"title"})
  - @Gedmo\Translatable
  - @ORM\Column(length=128, unique=false)
    */
    private $slug;
    
    // ... rest of the entity
    }

I've read something about having the SluggableListener before the TranslatableListener so I changed the doctrine_extensions.yml (imported from config.yml) :

```
# KernelRequest listener ....

#Doctrine Extension listeners to handle behaviors
gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.translatable:
    class: Gedmo\Translatable\TranslatableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
        - [ setDefaultLocale, [ %locale% ] ]
        - [ setTranslationFallback, [ false ] ]

 #other listeners ...
```

Still, when creating an object and translating it, the translations are well done except for the slug that doesn't appears in the translation table and stay in the News table in the default locale ...

Is that a bug on did I missed something ?
