### ISSUE TITLE
Slug is not translated for default locale

### ISSUE THREAD

**Issue by rodrigobb** [doctrine-extensions/DoctrineExtensions#570]
I'm using Translatable and Sluggable behaviour in my entities.

With the following service configuration, my entities' translatable fields are translated to all languages but the slug.

```
gedmo.listener.translatable:
    class: Gedmo\Translatable\TranslatableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ @annotation_reader ] ]
      - [ setDefaultLocale, [ %locale% ] ]
      - [ setTranslationFallback, [ true ] ]
      - [ setPersistDefaultLocaleTranslation, [ true ] ]
```

For example, 'title', 'slug' and 'subtitle' are translatable and I get 3 translations (es, it, en) for 'title' and 'subtitle' but only 2 (it,en) for slug, missing 'es' which is my 'default_locale'.

```
/**
* @var string $title
*
* @Gedmo\Translatable
* @ORM\Column(name="title", type="string", length=255)
*/
private $title;

/**
* @var string $slug
*
* @Gedmo\Translatable
* @Gedmo\Slug(fields={"title"})
* @ORM\Column(name="slug", type="string", length=255, unique=true)
*/
private $slug;


/**
* @var string $subtitle
*
* Assert\NotBlank();
* @Gedmo\Translatable
* @ORM\Column(name="subtitle", type="string", length=255, nullable=true)
*/

```
