### ISSUE TITLE
Can't get an extension working with YAML mapping

### ISSUE THREAD

**Issue by mnapoli** [doctrine-extensions/DoctrineExtensions#671]
Hi,

I have tried several times, reading through the docs, examples, code and tests each time, but I really can't get the extensions to work with YAML mapping. There is not enough docs about that, and I'd be happy to add them if you can't help me get it to work.

Here is my `.yml` mapping file:

``` yml
MyClass:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      gedmo:
        - translatable
```

I added the event listener:

``` php
$evm = new Doctrine\Common\EventManager();
$translatableListener = new Gedmo\Translatable\TranslatableListener();
$evm->addEventSubscriber($translatableListener);

$em = Doctrine\ORM\EntityManager::create($connection, $config, $evm);
```

Is that all I have to configure?

In the examples and docs, it seems all the rest is configuration for annotations, so I guess I can skip it because I want to map everything with YAML.

Here is the error I get:

```
Doctrine\Common\Persistence\Mapping\MappingException : No mapping file found named 'Gedmo.Translatable.Entity.Translation.yml' for class 'Gedmo\Translatable\Entity\Translation'.
```
