### ISSUE TITLE
slug: Does not work on Symfony 2.2

### ISSUE THREAD

**Issue by zeitnot** [doctrine-extensions/DoctrineExtensions#711]
Hi,

The slug behaviour does not work on Symfony 2.2 with mongodb.

My document: 

```
        namespace Tf\CommonBundle\Document;

        use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
        use Gedmo\Mapping\Annotation as Gedmo;

        /**
         * @MongoDB\Document(
         *   collection="deals"
         * )
         * 
         */

        Class Deal{

            /**
             * @MongoDB\Id
             */

            protected $id;

            /**
             * @MongoDB\String
             */

            protected $title;

            /**
             * @MongoDB\String
             * 
             */

            protected $link;

            /**
             * @MongoDB\Collection
             */

            protected $descriptions = array();

            /**
             *@MongoDB\String
             */

            protected $image;

            /**
             * @MongoDB\String
             */

            protected $currency;

            /**
             * @MongoDB\Boolean
             */

            protected $status = false;

            /**
             * @Gedmo\Slug(fields={"title"})
             * @MongoDB\String
             */

            protected $slug;
```

my config: 

```
    # services to handle doctrine extensions
    services:
        gedmo.listener.timestampable:
            class: Gedmo\Timestampable\TimestampableListener
            tags:
                - { name: doctrine.event_subscriber, connection: default }
            calls:
                - [ setAnnotationReader, [ "@annotation_reader" ] ]

        gedmo.listener.sluggable:
            class: Gedmo\Sluggable\SluggableListener
            tags:
                - { name: doctrine.event_subscriber, connection: default }
            calls:
                - [ setAnnotationReader, [ "@annotation_reader" ] ]
```
