### ISSUE TITLE
setDefaultLocale does not seem to work propertly

### ISSUE THREAD

**Issue by varas** [doctrine-extensions/DoctrineExtensions#725]
Having request locale "es_ES" and so Listener config:

```
gedmo.listener.translatable:
    class: Gedmo\Translatable\TranslatableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
        - [ setDefaultLocale, 'es_ES' ]
        - [ setTranslationFallback, [ false ] ]
```

It stores an entry at TranslationEntity having locale 'en_US'

Why?
