### ISSUE TITLE
[Loggable] yaml mapping driver for relations

### ISSUE THREAD

**Issue by 1ed** [doctrine-extensions/DoctrineExtensions#94]
This is not works with yaml annotations:

```
    manyToOne:
        customer:
            targetEntity: Customer
            gedmo:
                versioned: true
```
